module.exports.PrefixLending = 'lending'
module.exports.BankMSPID = 'BankMSP'
module.exports.FicoMSPID = 'FicoMSP'
module.exports.InsuranceMSPID = 'InsuranceMSP'
module.exports.AppraiserMSPID = 'AppraiserMSP'
module.exports.RevenueMSPID = 'RevenueMSP'
module.exports.RegistryMSPID = 'RegistryMSP'
