OrdererOrgs:
  - Name: OrdererOrg
    Domain: orderer-org
    Specs:
      - Hostname: orderer0
        CommonName: '{{.Hostname}}'
PeerOrgs:
  - Name: AppraiserOrg
    Domain: appraiser-org
    EnableNodeOUs: true
    Specs:
      - Hostname: appraiser-peer
        CommonName: '{{.Hostname}}'
  - Name: AuditOrg
    Domain: audit-org
    EnableNodeOUs: true
    Specs:
      - Hostname: audit-peer
        CommonName: '{{.Hostname}}'
  - Name: BankOrg
    Domain: bank-org
    EnableNodeOUs: true
    Specs:
      - Hostname: bank-peer
        CommonName: '{{.Hostname}}'
  - Name: FicoOrg
    Domain: fico-org
    EnableNodeOUs: true
    Specs:
      - Hostname: fico-peer
        CommonName: '{{.Hostname}}'
  - Name: InsuranceOrg
    Domain: insurance-org
    EnableNodeOUs: true
    Specs:
      - Hostname: insurance-peer
        CommonName: '{{.Hostname}}'
  - Name: MunicipalOrg
    Domain: municipal-org
    EnableNodeOUs: true
    Specs:
      - Hostname: municipal-peer
        CommonName: '{{.Hostname}}'
  - Name: RegistryOrg
    Domain: registry-org
    EnableNodeOUs: true
    Specs:
      - Hostname: registry-peer
        CommonName: '{{.Hostname}}'
  - Name: RevenueOrg
    Domain: revenue-org
    EnableNodeOUs: true
    Specs:
      - Hostname: revenue-peer
        CommonName: '{{.Hostname}}'
