version: '2'

networks:
  landrecord:
    name: fabric_landrecord

services:
  appraiser-couchdb:
    container_name: appraiser-couchdb
    extends:
      file: ./base/db-base.yaml
      service: db-base
    networks:
      - landrecord

  audit-couchdb:
    container_name: audit-couchdb
    extends:
      file: ./base/db-base.yaml
      service: db-base
    networks:
      - landrecord

  bank-couchdb:
    container_name: bank-couchdb
    extends:
      file: ./base/db-base.yaml
      service: db-base
    networks:
      - landrecord

  fico-couchdb:
    container_name: fico-couchdb
    extends:
      file: ./base/db-base.yaml
      service: db-base
    networks:
      - landrecord

  insurance-couchdb:
    container_name: insurance-couchdb
    extends:
      file: ./base/db-base.yaml
      service: db-base
    networks:
      - landrecord

  municipal-couchdb:
    container_name: municipal-couchdb
    extends:
      file: ./base/db-base.yaml
      service: db-base
    networks:
      - landrecord

  registry-couchdb:
    container_name: registry-couchdb
    extends:
      file: ./base/db-base.yaml
      service: db-base
    networks:
      - landrecord
  
  revenue-couchdb:
    container_name: revenue-couchdb
    extends:
      file: ./base/db-base.yaml
      service: db-base
    networks:
      - landrecord

  appraiser-ca:
    container_name: appraiser-ca
    extends:
      file: ./base/ca-base.yaml
      service: ca-base
    image: appraiser-ca
    ports:
    - 7054:7054
    networks:
      - landrecord
    
  audit-ca:
    container_name: audit-ca
    extends:
      file: ./base/ca-base.yaml
      service: ca-base
    image: audit-ca
    ports:
    - 8054:8054
    networks:
      - landrecord
    
  bank-ca:
    container_name: bank-ca
    extends:
      file: ./base/ca-base.yaml
      service: ca-base
    image: bank-ca
    ports:
    - 9054:9054
    networks:
      - landrecord

  fico-ca:
    container_name: fico-ca
    extends:
      file: ./base/ca-base.yaml
      service: ca-base
    image: fico-ca
    ports:
    - 10054:10054
    networks:
      - landrecord
  
  insurance-ca:
    container_name: insurance-ca
    extends:
      file: ./base/ca-base.yaml
      service: ca-base
    image: insurance-ca
    ports:
    - 11054:11054
    networks:
      - landrecord
  
  municipal-ca:
    container_name: municipal-ca
    extends:
      file: ./base/ca-base.yaml
      service: ca-base
    image: municipal-ca
    ports:
    - 12054:12054
    networks:
      - landrecord

  registry-ca:
    container_name: registry-ca
    extends:
      file: ./base/ca-base.yaml
      service: ca-base
    image: registry-ca
    ports:
    - 13054:13054
    networks:
      - landrecord
  
  revenue-ca:
    container_name: revenue-ca
    extends:
      file: ./base/ca-base.yaml
      service: ca-base
    image: revenue-ca
    ports:
    - 14054:14054
    networks:
      - landrecord

  orderer-ca:
    container_name: orderer-ca
    extends:
      file: ./base/ca-base.yaml
      service: ca-base
    image: orderer-ca
    ports:
    - 15054:15054
    networks:
      - landrecord

  orderer0:
    container_name: orderer0
    image: orderer
    environment:
    - FABRIC_LOGGING_SPEC=INFO
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
    - ORDERER_GENERAL_LISTENPORT=7050
    - ORDERER_GENERAL_BOOTSTRAPFILE=/orderer/crypto/genesis.block
    - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
    - ORDERER_GENERAL_LOCALMSPDIR=/orderer/crypto/msp
    - ORDERER_GENERAL_TLS_ENABLED=true
    - ORDERER_GENERAL_TLS_PRIVATEKEY=/orderer/crypto/tls/server.key
    - ORDERER_GENERAL_TLS_CERTIFICATE=/orderer/crypto/tls/server.crt
    - ORDERER_GENERAL_TLS_ROOTCAS=/orderer/crypto/tls/ca.crt
    # - ORDERER_GENERAL_TLS_CLIENTAUTHREQUIRED=true
    # - ORDERER_GENERAL_TLS_CLIENTROOTCAS=/orderer/crypto/tls/ca.crt
    - ORDERER_OPERATIONS_LISTENADDRESS=orderer0:7049
    - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /orderer
    command: orderer
    ports:
    - 7050:7050
    - 7049:7049
    depends_on:
    - orderer-ca
    networks:
      - landrecord

  appraiser-peer:
    container_name: appraiser-peer
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    image: appraiser-peer
    environment:
    - CORE_PEER_ID=appraiser-peer
    - CORE_PEER_ADDRESS=appraiser-peer:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=appraiser-peer:7051
    - CORE_PEER_LOCALMSPID=AppraiserMSP
    - CORE_PEER_GOSSIP_BOOTSTRAP=appraiser-peer:7051
    - CORE_OPERATIONS_LISTENADDRESS=appraiser-peer:7053
    - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
    - CORE_PEER_CHAINCODEADDRESS=appraiser-peer:7052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=appraiser-couchdb:5984
    - CORE_METRICS_PROVIDER=prometheus
    ports:
    - 7051:7051
    - 7053:7053
    depends_on:
    - orderer0
    - appraiser-ca
    - appraiser-couchdb
    networks:
      - landrecord
  
  audit-peer:
    container_name: audit-peer
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    image: audit-peer
    environment:
    - CORE_PEER_ID=audit-peer
    - CORE_PEER_ADDRESS=audit-peer:8051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=audit-peer:8051
    - CORE_PEER_LOCALMSPID=AuditMSP
    - CORE_PEER_GOSSIP_BOOTSTRAP=audit-peer:8051
    - CORE_OPERATIONS_LISTENADDRESS=audit-peer:8053
    - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
    - CORE_PEER_CHAINCODEADDRESS=audit-peer:8052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=audit-couchdb:5984
    - CORE_METRICS_PROVIDER=prometheus
    ports:
    - 8051:8051
    - 8053:8053
    depends_on:
    - orderer0
    - audit-ca
    - audit-couchdb
    networks:
      - landrecord
  
  bank-peer:
    container_name: bank-peer
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    image: bank-peer
    environment:
    - CORE_PEER_ID=bank-peer
    - CORE_PEER_ADDRESS=bank-peer:9051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=bank-peer:9051
    - CORE_PEER_LOCALMSPID=BankMSP
    - CORE_PEER_GOSSIP_BOOTSTRAP=bank-peer:9051
    - CORE_OPERATIONS_LISTENADDRESS=bank-peer:9053
    - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
    - CORE_PEER_CHAINCODEADDRESS=bank-peer:9052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=bank-couchdb:5984
    - CORE_METRICS_PROVIDER=prometheus
    ports:
    - 9051:9051
    - 9053:9053
    depends_on:
    - orderer0
    - bank-ca
    - bank-couchdb
    networks:
      - landrecord

  fico-peer:
    container_name: fico-peer
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    image: fico-peer
    environment:
    - CORE_PEER_ID=fico-peer
    - CORE_PEER_ADDRESS=fico-peer:10051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=fico-peer:10051
    - CORE_PEER_LOCALMSPID=FicoMSP
    - CORE_PEER_GOSSIP_BOOTSTRAP=fico-peer:10051
    - CORE_OPERATIONS_LISTENADDRESS=fico-peer:10053
    - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
    - CORE_PEER_CHAINCODEADDRESS=fico-peer:10052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=fico-couchdb:5984
    - CORE_METRICS_PROVIDER=prometheus
    ports:
    - 10051:10051
    - 10053:10053
    depends_on:
    - orderer0
    - fico-ca
    - fico-couchdb
    networks:
      - landrecord

  insurance-peer:
    container_name: insurance-peer
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    image: insurance-peer
    environment:
    - CORE_PEER_ID=insurance-peer
    - CORE_PEER_ADDRESS=insurance-peer:11051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=insurance-peer:11051
    - CORE_PEER_LOCALMSPID=InsuranceMSP
    - CORE_PEER_GOSSIP_BOOTSTRAP=insurance-peer:11051
    - CORE_OPERATIONS_LISTENADDRESS=insurance-peer:11053
    - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
    - CORE_PEER_CHAINCODEADDRESS=insurance-peer:11052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=insurance-couchdb:5984
    - CORE_METRICS_PROVIDER=prometheus
    ports:
    - 11051:11051
    - 11053:11053
    depends_on:
    - orderer0
    - insurance-ca
    - insurance-couchdb
    networks:
      - landrecord

  municipal-peer:
    container_name: municipal-peer
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    image: municipal-peer
    environment:
    - CORE_PEER_ID=municipal-peer
    - CORE_PEER_ADDRESS=municipal-peer:12051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=municipal-peer:12051
    - CORE_PEER_LOCALMSPID=MunicipalMSP
    - CORE_PEER_GOSSIP_BOOTSTRAP=municipal-peer:12051
    - CORE_OPERATIONS_LISTENADDRESS=municipal-peer:12053
    - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
    - CORE_PEER_CHAINCODEADDRESS=municipal-peer:12052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=municipal-couchdb:5984
    - CORE_METRICS_PROVIDER=prometheus
    ports:
    - 12051:12051
    - 12053:12053
    depends_on:
    - orderer0
    - municipal-ca
    - municipal-couchdb
    networks:
      - landrecord
  
  registry-peer:
    container_name: registry-peer
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    image: registry-peer
    environment:
    - CORE_PEER_ID=registry-peer
    - CORE_PEER_ADDRESS=registry-peer:13051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=registry-peer:13051
    - CORE_PEER_LOCALMSPID=RegistryMSP
    - CORE_PEER_GOSSIP_BOOTSTRAP=registry-peer:13051
    - CORE_OPERATIONS_LISTENADDRESS=registry-peer:13053
    - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
    - CORE_PEER_CHAINCODEADDRESS=registry-peer:13052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13052
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=registry-couchdb:5984
    - CORE_METRICS_PROVIDER=prometheus
    ports:
    - 13051:13051
    - 13053:13053
    depends_on:
    - orderer0
    - registry-ca
    - registry-couchdb
    networks:
      - landrecord
  
  revenue-peer:
    container_name: revenue-peer
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    image: revenue-peer
    environment:
    - CORE_PEER_ID=revenue-peer
    - CORE_PEER_ADDRESS=revenue-peer:14051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=revenue-peer:14051
    - CORE_PEER_LOCALMSPID=RevenueMSP
    - CORE_PEER_GOSSIP_BOOTSTRAP=revenue-peer:14051
    - CORE_OPERATIONS_LISTENADDRESS=revenue-peer:14053
    - CORE_PEER_LISTENADDRESS=0.0.0.0:14051
    - CORE_PEER_CHAINCODEADDRESS=revenue-peer:14052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:14052
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=revenue-couchdb:5984
    - CORE_METRICS_PROVIDER=prometheus
    ports:
    - 14051:14051
    - 14053:14053
    depends_on:
    - orderer0
    - revenue-ca
    - revenue-couchdb
    networks:
      - landrecord
  
  appraiser-cli:
    extends:
      file: ./base/cli-base.yaml
      service: cli-base
    container_name: appraiser-cli
    environment:
      - CORE_PEER_ID=appraiser-cli
      - CORE_PEER_ADDRESS=appraiser-peer:7051
      - CORE_PEER_LOCALMSPID=AppraiserMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@appraiser-org/msp
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/users/Admin@appraiser-org/tls/ca.crt
      - ORDERER_TLS_CLIENTCERT_FILE=/etc/hyperledger/msp/users/Admin@appraiser-org/tls/client.crt
      - ORDERER_TLS_CLIENTKEY_FILE=/etc/hyperledger/msp/users/Admin@appraiser-org/tls/client.key
    volumes:
      - ./artifacts/crypto-config/peerOrganizations/appraiser-org:/etc/hyperledger/msp
    depends_on:
      - orderer0
      - appraiser-peer
    networks:
      - landrecord

  audit-cli:
    extends:
      file: ./base/cli-base.yaml
      service: cli-base
    container_name: audit-cli
    environment:
      - CORE_PEER_ID=audit-cli
      - CORE_PEER_ADDRESS=audit-peer:8051
      - CORE_PEER_LOCALMSPID=AuditMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@audit-org/msp
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/users/Admin@audit-org/tls/ca.crt
      - ORDERER_TLS_CLIENTCERT_FILE=/etc/hyperledger/msp/users/Admin@audit-org/tls/client.crt
      - ORDERER_TLS_CLIENTKEY_FILE=/etc/hyperledger/msp/users/Admin@audit-org/tls/client.key
    volumes:
      - ./artifacts/crypto-config/peerOrganizations/audit-org:/etc/hyperledger/msp
    depends_on:
      - orderer0
      - audit-peer
    networks:
      - landrecord

  bank-cli:
    extends:
      file: ./base/cli-base.yaml
      service: cli-base
    container_name: bank-cli
    environment:
      - CORE_PEER_ID=bank-cli
      - CORE_PEER_ADDRESS=bank-peer:9051
      - CORE_PEER_LOCALMSPID=BankMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@bank-org/msp
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/users/Admin@bank-org/tls/ca.crt
      - ORDERER_TLS_CLIENTCERT_FILE=/etc/hyperledger/msp/users/Admin@bank-org/tls/client.crt
      - ORDERER_TLS_CLIENTKEY_FILE=/etc/hyperledger/msp/users/Admin@bank-org/tls/client.key
    volumes:
      - ./artifacts/crypto-config/peerOrganizations/bank-org:/etc/hyperledger/msp
    depends_on:
      - orderer0
      - bank-peer
    networks:
      - landrecord

  fico-cli:
    extends:
      file: ./base/cli-base.yaml
      service: cli-base
    container_name: fico-cli
    environment:
      - CORE_PEER_ID=fico-cli
      - CORE_PEER_ADDRESS=fico-peer:10051
      - CORE_PEER_LOCALMSPID=FicoMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@fico-org/msp
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/users/Admin@fico-org/tls/ca.crt
      - ORDERER_TLS_CLIENTCERT_FILE=/etc/hyperledger/msp/users/Admin@fico-org/tls/client.crt
      - ORDERER_TLS_CLIENTKEY_FILE=/etc/hyperledger/msp/users/Admin@fico-org/tls/client.key
    volumes:
      - ./artifacts/crypto-config/peerOrganizations/fico-org:/etc/hyperledger/msp
    depends_on:
      - orderer0
      - fico-peer
    networks:
      - landrecord

  insurance-cli:
    extends:
      file: ./base/cli-base.yaml
      service: cli-base
    container_name: insurance-cli
    environment:
      - CORE_PEER_ID=insurance-cli
      - CORE_PEER_ADDRESS=insurance-peer:11051
      - CORE_PEER_LOCALMSPID=InsuranceMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@insurance-org/msp
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/users/Admin@insurance-org/tls/ca.crt
      - ORDERER_TLS_CLIENTCERT_FILE=/etc/hyperledger/msp/users/Admin@insurance-org/tls/client.crt
      - ORDERER_TLS_CLIENTKEY_FILE=/etc/hyperledger/msp/users/Admin@insurance-org/tls/client.key
    volumes:
      - ./artifacts/crypto-config/peerOrganizations/insurance-org:/etc/hyperledger/msp
    depends_on:
      - orderer0
      - insurance-peer
    networks:
      - landrecord

  municipal-cli:
    extends:
      file: ./base/cli-base.yaml
      service: cli-base
    container_name: municipal-cli
    environment:
      - CORE_PEER_ID=municipal-cli
      - CORE_PEER_ADDRESS=municipal-peer:12051
      - CORE_PEER_LOCALMSPID=MunicipalMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@municipal-org/msp
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/users/Admin@municipal-org/tls/ca.crt
      - ORDERER_TLS_CLIENTCERT_FILE=/etc/hyperledger/msp/users/Admin@municipal-org/tls/client.crt
      - ORDERER_TLS_CLIENTKEY_FILE=/etc/hyperledger/msp/users/Admin@municipal-org/tls/client.key
    volumes:
      - ./artifacts/crypto-config/peerOrganizations/municipal-org:/etc/hyperledger/msp
    depends_on:
      - orderer0
      - municipal-peer
    networks:
      - landrecord

  registry-cli:
    extends:
      file: ./base/cli-base.yaml
      service: cli-base
    container_name: registry-cli
    environment:
      - CORE_PEER_ID=registry-cli
      - CORE_PEER_ADDRESS=registry-peer:13051
      - CORE_PEER_LOCALMSPID=RegistryMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@registry-org/msp
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/users/Admin@registry-org/tls/ca.crt
      - ORDERER_TLS_CLIENTCERT_FILE=/etc/hyperledger/msp/users/Admin@registry-org/tls/client.crt
      - ORDERER_TLS_CLIENTKEY_FILE=/etc/hyperledger/msp/users/Admin@registry-org/tls/client.key
    volumes:
      - ./artifacts/crypto-config/peerOrganizations/registry-org:/etc/hyperledger/msp
    depends_on:
      - orderer0
      - registry-peer
    networks:
      - landrecord

  revenue-cli:
    extends:
      file: ./base/cli-base.yaml
      service: cli-base
    container_name: revenue-cli
    environment:
      - CORE_PEER_ID=revenue-cli
      - CORE_PEER_ADDRESS=revenue-peer:14051
      - CORE_PEER_LOCALMSPID=RevenueMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@revenue-org/msp
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/users/Admin@revenue-org/tls/ca.crt
      - ORDERER_TLS_CLIENTCERT_FILE=/etc/hyperledger/msp/users/Admin@revenue-org/tls/client.crt
      - ORDERER_TLS_CLIENTKEY_FILE=/etc/hyperledger/msp/users/Admin@revenue-org/tls/client.key
    volumes:
      - ./artifacts/crypto-config/peerOrganizations/revenue-org:/etc/hyperledger/msp
    depends_on:
      - orderer0
      - revenue-peer
    networks:
      - landrecord
