version: '2'

networks:
  landrecord:
    name: fabric_landrecord

services:
  appraiser-ca:
    container_name: appraiser-ca
    extends:
      file: ./base/ca-base.yaml
      service: ca-base
    image: appraiser-ca
    ports:
    - 7054:7054
    networks:
      - landrecord
    
  audit-ca:
    container_name: audit-ca
    extends:
      file: ./base/ca-base.yaml
      service: ca-base
    image: audit-ca
    ports:
    - 8054:7054
    networks:
      - landrecord
    
  bank-ca:
    container_name: bank-ca
    extends:
      file: ./base/ca-base.yaml
      service: ca-base
    image: bank-ca
    ports:
    - 9054:7054
    networks:
      - landrecord

  fico-ca:
    container_name: fico-ca
    extends:
      file: ./base/ca-base.yaml
      service: ca-base
    image: fico-ca
    ports:
    - 10054:7054
    networks:
      - landrecord
  
  insurance-ca:
    container_name: insurance-ca
    extends:
      file: ./base/ca-base.yaml
      service: ca-base
    image: insurance-ca
    ports:
    - 11054:7054
    networks:
      - landrecord

  registry-ca:
    container_name: registry-ca
    extends:
      file: ./base/ca-base.yaml
      service: ca-base
    image: registry-ca
    ports:
    - 12054:7054
    networks:
      - landrecord
  
  title-ca:
    container_name: title-ca
    extends:
      file: ./base/ca-base.yaml
      service: ca-base
    image: title-ca
    ports:
    - 13054:7054
    networks:
      - landrecord

  orderer0:
    container_name: orderer0
    image: orderer
    environment:
    - ORDERER_GENERAL_LOGLEVEL=debug
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_GENESISMETHOD=file
    - ORDERER_GENERAL_GENESISFILE=/orderer/crypto/genesis.block
    - ORDERER_GENERAL_LOCALMSPID=OrdererOrgMSP
    - ORDERER_GENERAL_LOCALMSPDIR=/orderer/crypto/msp
    - ORDERER_GENERAL_TLS_ENABLED=true
    - ORDERER_GENERAL_TLS_PRIVATEKEY=/orderer/crypto/tls/server.key
    - ORDERER_GENERAL_TLS_CERTIFICATE=/orderer/crypto/tls/server.crt
    - ORDERER_GENERAL_TLS_ROOTCAS=[/orderer/crypto/tls/ca.crt]
    working_dir: /orderer
    command: orderer
    ports:
    - 7050:7050
    networks:
      - landrecord

    appraiser-peer:
    container_name: appraiser-peer
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    image: appraiser-peer
    environment:
    - CORE_PEER_ID=appraiser-peer
    - CORE_PEER_ADDRESS=appraiser-peer:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=appraiser-peer:7051
    - CORE_PEER_LOCALMSPID=AppraiserOrgMSP
    ports:
    - 7051:7051
    - 7053:7053
    depends_on:
    - orderer0
    networks:
      - landrecord
  
  audit-peer:
    container_name: audit-peer
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    image: audit-peer
    environment:
    - CORE_PEER_ID=audit-peer
    - CORE_PEER_ADDRESS=audit-peer:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=audit-peer:7051
    - CORE_PEER_LOCALMSPID=AuditOrgMSP
    ports:
    - 8051:7051
    - 8053:7053
    depends_on:
    - orderer0
    - appraiser-peer
    networks:
      - landrecord
  
  bank-peer:
    container_name: bank-peer
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    image: bank-peer
    environment:
    - CORE_PEER_ID=bank-peer
    - CORE_PEER_ADDRESS=bank-peer:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=bank-peer:7051
    - CORE_PEER_LOCALMSPID=BankOrgMSP
    ports:
    - 9051:7051
    - 9053:7053
    depends_on:
    - orderer0
    - appraiser-peer
    - audit-peer
    networks:
      - landrecord

  fico-peer:
    container_name: fico-peer
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    image: fico-peer
    environment:
    - CORE_PEER_ID=fico-peer
    - CORE_PEER_ADDRESS=fico-peer:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=fico-peer:7051
    - CORE_PEER_LOCALMSPID=FicoOrgMSP
    ports:
    - 10051:7051
    - 10053:7053
    depends_on:
    - orderer0
    - appraiser-peer
    - audit-peer
    - bank-peer
    networks:
      - landrecord

  insurance-peer:
    container_name: insurance-peer
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    image: insurance-peer
    environment:
    - CORE_PEER_ID=insurance-peer
    - CORE_PEER_ADDRESS=insurance-peer:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=insurance-peer:7051
    - CORE_PEER_LOCALMSPID=InsuranceOrgMSP
    ports:
    - 11051:7051
    - 11053:7053
    depends_on:
    - orderer0
    - appraiser-peer
    - audit-peer
    - bank-peer
    - fico-peer
    networks:
      - landrecord
  
  registry-peer:
    container_name: registry-peer
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    image: registry-peer
    environment:
    - CORE_PEER_ID=registry-peer
    - CORE_PEER_ADDRESS=registry-peer:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=registry-peer:7051
    - CORE_PEER_LOCALMSPID=RegistryOrgMSP
    ports:
    - 12051:7051
    - 12053:7053
    depends_on:
    - orderer0
    - appraiser-peer
    - audit-peer
    - bank-peer
    - fico-peer
    - insurance-peer
    networks:
      - landrecord
  
  title-peer:
    container_name: title-peer
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    image: title-peer
    environment:
    - CORE_PEER_ID=title-peer
    - CORE_PEER_ADDRESS=title-peer:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=title-peer:7051
    - CORE_PEER_LOCALMSPID=TitleOrgMSP
    ports:
    - 13051:7051
    - 13053:7053
    depends_on:
    - orderer0
    - appraiser-peer
    - audit-peer
    - bank-peer
    - fico-peer
    - insurance-peer
    - registry-peer
    networks:
      - landrecord
  
  bank-cli:
    extends:
      file: ./base/cli-base.yaml
      service: cli
    container_name: bank-cli
    environment:
      - CORE_PEER_ID=bank-cli
      - CORE_PEER_ADDRESS=bank-peer:7051
      - CORE_PEER_LOCALMSPID=BankOrgMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@bank-org/msp
    volumes:
      - ./artifacts/crypto-config/peerOrganizations/bank-org:/etc/hyperledger/msp
    depends_on:
      - orderer0
      - bank-peer
    networks:
      - landrecord

  insurance-cli:
    extends:
      file: ./base/cli-base.yaml
      service: cli
    container_name: insurance-cli
    environment:
      - CORE_PEER_ID=insurance-cli
      - CORE_PEER_ADDRESS=insurance-peer:7051
      - CORE_PEER_LOCALMSPID=InsuranceOrgMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@insurance-org/msp
    volumes:
      - ./artifacts/crypto-config/peerOrganizations/insurance-org:/etc/hyperledger/msp
    depends_on:
      - orderer0
      - insurance-peer
    networks:
      - landrecord

  registry-cli:
    extends:
      file: ./base/cli-base.yaml
      service: cli
    container_name: registry-cli
    environment:
      - CORE_PEER_ID=registry-cli
      - CORE_PEER_ADDRESS=registry-peer:7051
      - CORE_PEER_LOCALMSPID=RegistryOrgMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@registry-org/msp
    volumes:
      - ./artifacts/crypto-config/peerOrganizations/registry-org:/etc/hyperledger/msp
    depends_on:
      - orderer0
      - registry-peer
    networks:
      - landrecord

  title-cli:
    extends:
      file: ./base/cli-base.yaml
      service: cli
    container_name: title-cli
    environment:
      - CORE_PEER_ID=title-cli
      - CORE_PEER_ADDRESS=title-peer:7051
      - CORE_PEER_LOCALMSPID=TitleOrgMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@title-org/msp
    volumes:
      - ./artifacts/crypto-config/peerOrganizations/title-org:/etc/hyperledger/msp
    depends_on:
      - orderer0
      - title-peer
    networks:
      - landrecord

  appraiser-cli:
    extends:
      file: ./base/cli-base.yaml
      service: cli
    container_name: appraiser-cli
    environment:
      - CORE_PEER_ID=appraiser-cli
      - CORE_PEER_ADDRESS=appraiser-peer:7051
      - CORE_PEER_LOCALMSPID=AppraiserOrgMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@appraiser-org/msp
    volumes:
      - ./artifacts/crypto-config/peerOrganizations/appraiser-org:/etc/hyperledger/msp
    depends_on:
      - orderer0
      - appraiser-peer
    networks:
      - landrecord

  audit-cli:
    extends:
      file: ./base/cli-base.yaml
      service: cli
    container_name: audit-cli
    environment:
      - CORE_PEER_ID=audit-cli
      - CORE_PEER_ADDRESS=audit-peer:7051
      - CORE_PEER_LOCALMSPID=AuditOrgMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@audit-org/msp
    volumes:
      - ./artifacts/crypto-config/peerOrganizations/audit-org:/etc/hyperledger/msp
    depends_on:
      - orderer0
      - audit-peer
    networks:
      - landrecord

  fico-cli:
    extends:
      file: ./base/cli-base.yaml
      service: cli
    container_name: fico-cli
    environment:
      - CORE_PEER_ID=fico-cli
      - CORE_PEER_ADDRESS=fico-peer:7051
      - CORE_PEER_LOCALMSPID=FicoOrgMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@fico-org/msp
    volumes:
      - ./artifacts/crypto-config/peerOrganizations/fico-org:/etc/hyperledger/msp
    depends_on:
      - orderer0
      - fico-peer
    networks:
      - landrecord


  # web:
  #   container_name: web
  #   image: web
  #   # TODO
  #   depends_on:
  #     - orderer0
  #     - appraiser-peer
  #     - audit-peer
  #     - bank-peer
  #     - fico-peer
  #     - insurance-peer
  #     - registry-peer
  #     - title-peer
  #   networks:
  #     - landrecord
