version: '2'

networks:
  landrecord:
    name: fabric_landrecord

services:
  appraiser-ca:
    container_name: appraiser-ca
    extends:
      file: ./base/ca-base.yaml
      service: ca-base
    image: appraiser-ca
    ports:
    - 7054:7054
    networks:
      - landrecord
    
  audit-ca:
    container_name: audit-ca
    extends:
      file: ./base/ca-base.yaml
      service: ca-base
    image: audit-ca
    ports:
    - 8054:8054
    networks:
      - landrecord
    
  bank-ca:
    container_name: bank-ca
    extends:
      file: ./base/ca-base.yaml
      service: ca-base
    image: bank-ca
    ports:
    - 9054:9054
    networks:
      - landrecord

  fico-ca:
    container_name: fico-ca
    extends:
      file: ./base/ca-base.yaml
      service: ca-base
    image: fico-ca
    ports:
    - 10054:10054
    networks:
      - landrecord
  
  insurance-ca:
    container_name: insurance-ca
    extends:
      file: ./base/ca-base.yaml
      service: ca-base
    image: insurance-ca
    ports:
    - 11054:11054
    networks:
      - landrecord

  registry-ca:
    container_name: registry-ca
    extends:
      file: ./base/ca-base.yaml
      service: ca-base
    image: registry-ca
    ports:
    - 12054:12054
    networks:
      - landrecord
  
  title-ca:
    container_name: title-ca
    extends:
      file: ./base/ca-base.yaml
      service: ca-base
    image: title-ca
    ports:
    - 13054:13054
    networks:
      - landrecord

  orderer-ca:
    container_name: orderer-ca
    extends:
      file: ./base/ca-base.yaml
      service: ca-base
    image: orderer-ca
    ports:
    - 14054:14054
    networks:
      - landrecord

  orderer0:
    container_name: orderer0
    image: orderer
    environment:
    - FABRIC_LOGGING_SPEC=INFO
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
    - ORDERER_GENERAL_LISTENPORT=7050
    - ORDERER_GENERAL_BOOTSTRAPFILE=/orderer/crypto/genesis.block
    - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
    - ORDERER_GENERAL_LOCALMSPDIR=/orderer/crypto/msp
    - ORDERER_GENERAL_TLS_ENABLED=true
    - ORDERER_GENERAL_TLS_PRIVATEKEY=/orderer/crypto/tls/server.key
    - ORDERER_GENERAL_TLS_CERTIFICATE=/orderer/crypto/tls/server.crt
    - ORDERER_GENERAL_TLS_ROOTCAS=/orderer/crypto/tls/ca.crt
    # - ORDERER_GENERAL_TLS_CLIENTAUTHREQUIRED=true
    # - ORDERER_GENERAL_TLS_CLIENTROOTCAS=/orderer/crypto/tls/ca.crt
    working_dir: /orderer
    command: orderer
    ports:
    - 7050:7050
    depends_on:
    - orderer-ca
    networks:
      - landrecord

  appraiser-peer:
    container_name: appraiser-peer
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    image: appraiser-peer
    environment:
    - CORE_PEER_ID=appraiser-peer
    - CORE_PEER_ADDRESS=appraiser-peer:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=appraiser-peer:7051
    - CORE_PEER_LOCALMSPID=AppraiserMSP
    - CORE_PEER_GOSSIP_BOOTSTRAP=appraiser-peer:7051
    - CORE_OPERATIONS_LISTENADDRESS=appraiser-peer:7053
    - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
    - CORE_PEER_CHAINCODEADDRESS=appraiser-peer:7052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
    ports:
    - 7051:7051
    - 7053:7053
    depends_on:
    - orderer0
    - appraiser-ca
    networks:
      - landrecord
  
  audit-peer:
    container_name: audit-peer
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    image: audit-peer
    environment:
    - CORE_PEER_ID=audit-peer
    - CORE_PEER_ADDRESS=audit-peer:8051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=audit-peer:8051
    - CORE_PEER_LOCALMSPID=AuditMSP
    - CORE_PEER_GOSSIP_BOOTSTRAP=audit-peer:8051
    - CORE_OPERATIONS_LISTENADDRESS=audit-peer:8053
    - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
    - CORE_PEER_CHAINCODEADDRESS=audit-peer:8052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
    ports:
    - 8051:8051
    - 8053:8053
    depends_on:
    - orderer0
    - audit-ca
    networks:
      - landrecord
  
  bank-peer:
    container_name: bank-peer
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    image: bank-peer
    environment:
    - CORE_PEER_ID=bank-peer
    - CORE_PEER_ADDRESS=bank-peer:9051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=bank-peer:9051
    - CORE_PEER_LOCALMSPID=BankMSP
    - CORE_PEER_GOSSIP_BOOTSTRAP=bank-peer:9051
    - CORE_OPERATIONS_LISTENADDRESS=bank-peer:9053
    - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
    - CORE_PEER_CHAINCODEADDRESS=bank-peer:9052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
    ports:
    - 9051:9051
    - 9053:9053
    depends_on:
    - orderer0
    - bank-ca
    networks:
      - landrecord

  fico-peer:
    container_name: fico-peer
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    image: fico-peer
    environment:
    - CORE_PEER_ID=fico-peer
    - CORE_PEER_ADDRESS=fico-peer:10051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=fico-peer:10051
    - CORE_PEER_LOCALMSPID=FicoMSP
    - CORE_PEER_GOSSIP_BOOTSTRAP=fico-peer:10051
    - CORE_OPERATIONS_LISTENADDRESS=fico-peer:10053
    - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
    - CORE_PEER_CHAINCODEADDRESS=fico-peer:10052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
    ports:
    - 10051:10051
    - 10053:10053
    depends_on:
    - orderer0
    - fico-ca
    networks:
      - landrecord

  insurance-peer:
    container_name: insurance-peer
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    image: insurance-peer
    environment:
    - CORE_PEER_ID=insurance-peer
    - CORE_PEER_ADDRESS=insurance-peer:11051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=insurance-peer:11051
    - CORE_PEER_LOCALMSPID=InsuranceMSP
    - CORE_PEER_GOSSIP_BOOTSTRAP=insurance-peer:11051
    - CORE_OPERATIONS_LISTENADDRESS=insurance-peer:11053
    - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
    - CORE_PEER_CHAINCODEADDRESS=insurance-peer:11052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
    ports:
    - 11051:11051
    - 11053:11053
    depends_on:
    - orderer0
    - insurance-ca
    networks:
      - landrecord
  
  registry-peer:
    container_name: registry-peer
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    image: registry-peer
    environment:
    - CORE_PEER_ID=registry-peer
    - CORE_PEER_ADDRESS=registry-peer:12051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=registry-peer:12051
    - CORE_PEER_LOCALMSPID=RegistryMSP
    - CORE_PEER_GOSSIP_BOOTSTRAP=registry-peer:12051
    - CORE_OPERATIONS_LISTENADDRESS=registry-peer:12053
    - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
    - CORE_PEER_CHAINCODEADDRESS=registry-peer:12052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
    ports:
    - 12051:12051
    - 12053:12053
    depends_on:
    - orderer0
    - registry-ca
    networks:
      - landrecord
  
  title-peer:
    container_name: title-peer
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    image: title-peer
    environment:
    - CORE_PEER_ID=title-peer
    - CORE_PEER_ADDRESS=title-peer:13051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=title-peer:13051
    - CORE_PEER_LOCALMSPID=TitleMSP
    - CORE_PEER_GOSSIP_BOOTSTRAP=title-peer:13051
    - CORE_OPERATIONS_LISTENADDRESS=title-peer:13053
    - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
    - CORE_PEER_CHAINCODEADDRESS=title-peer:13052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13052
    ports:
    - 13051:13051
    - 13053:13053
    depends_on:
    - orderer0
    - title-ca
    networks:
      - landrecord
  
  bank-cli:
    extends:
      file: ./base/cli-base.yaml
      service: cli
    container_name: bank-cli
    environment:
      - CORE_PEER_ID=bank-cli
      - CORE_PEER_ADDRESS=bank-peer:9051
      - CORE_PEER_LOCALMSPID=BankMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@bank-org/msp
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/users/Admin@bank-org/tls/ca.crt
      - ORDERER_TLS_CLIENTCERT_FILE=/etc/hyperledger/msp/users/Admin@bank-org/tls/client.crt
      - ORDERER_TLS_CLIENTKEY_FILE=/etc/hyperledger/msp/users/Admin@bank-org/tls/client.key
    volumes:
      - ./artifacts/crypto-config/peerOrganizations/bank-org:/etc/hyperledger/msp
    depends_on:
      - orderer0
      - bank-peer
    networks:
      - landrecord

  insurance-cli:
    extends:
      file: ./base/cli-base.yaml
      service: cli
    container_name: insurance-cli
    environment:
      - CORE_PEER_ID=insurance-cli
      - CORE_PEER_ADDRESS=insurance-peer:11051
      - CORE_PEER_LOCALMSPID=InsuranceMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@insurance-org/msp
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/users/Admin@insurance-org/tls/ca.crt
      - ORDERER_TLS_CLIENTCERT_FILE=/etc/hyperledger/msp/users/Admin@insurance-org/tls/client.crt
      - ORDERER_TLS_CLIENTKEY_FILE=/etc/hyperledger/msp/users/Admin@insurance-org/tls/client.key
    volumes:
      - ./artifacts/crypto-config/peerOrganizations/insurance-org:/etc/hyperledger/msp
    depends_on:
      - orderer0
      - insurance-peer
    networks:
      - landrecord

  registry-cli:
    extends:
      file: ./base/cli-base.yaml
      service: cli
    container_name: registry-cli
    environment:
      - CORE_PEER_ID=registry-cli
      - CORE_PEER_ADDRESS=registry-peer:12051
      - CORE_PEER_LOCALMSPID=RegistryMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@registry-org/msp
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/users/Admin@registry-org/tls/ca.crt
      - ORDERER_TLS_CLIENTCERT_FILE=/etc/hyperledger/msp/users/Admin@registry-org/tls/client.crt
      - ORDERER_TLS_CLIENTKEY_FILE=/etc/hyperledger/msp/users/Admin@registry-org/tls/client.key
    volumes:
      - ./artifacts/crypto-config/peerOrganizations/registry-org:/etc/hyperledger/msp
    depends_on:
      - orderer0
      - registry-peer
    networks:
      - landrecord

  title-cli:
    extends:
      file: ./base/cli-base.yaml
      service: cli
    container_name: title-cli
    environment:
      - CORE_PEER_ID=title-cli
      - CORE_PEER_ADDRESS=title-peer:13051
      - CORE_PEER_LOCALMSPID=TitleMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@title-org/msp
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/users/Admin@title-org/tls/ca.crt
      - ORDERER_TLS_CLIENTCERT_FILE=/etc/hyperledger/msp/users/Admin@title-org/tls/client.crt
      - ORDERER_TLS_CLIENTKEY_FILE=/etc/hyperledger/msp/users/Admin@title-org/tls/client.key
    volumes:
      - ./artifacts/crypto-config/peerOrganizations/title-org:/etc/hyperledger/msp
    depends_on:
      - orderer0
      - title-peer
    networks:
      - landrecord

  appraiser-cli:
    extends:
      file: ./base/cli-base.yaml
      service: cli
    container_name: appraiser-cli
    environment:
      - CORE_PEER_ID=appraiser-cli
      - CORE_PEER_ADDRESS=appraiser-peer:7051
      - CORE_PEER_LOCALMSPID=AppraiserMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@appraiser-org/msp
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/users/Admin@appraiser-org/tls/ca.crt
      - ORDERER_TLS_CLIENTCERT_FILE=/etc/hyperledger/msp/users/Admin@appraiser-org/tls/client.crt
      - ORDERER_TLS_CLIENTKEY_FILE=/etc/hyperledger/msp/users/Admin@appraiser-org/tls/client.key
    volumes:
      - ./artifacts/crypto-config/peerOrganizations/appraiser-org:/etc/hyperledger/msp
    depends_on:
      - orderer0
      - appraiser-peer
    networks:
      - landrecord

  audit-cli:
    extends:
      file: ./base/cli-base.yaml
      service: cli
    container_name: audit-cli
    environment:
      - CORE_PEER_ID=audit-cli
      - CORE_PEER_ADDRESS=audit-peer:8051
      - CORE_PEER_LOCALMSPID=AuditMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@audit-org/msp
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/users/Admin@audit-org/tls/ca.crt
      - ORDERER_TLS_CLIENTCERT_FILE=/etc/hyperledger/msp/users/Admin@audit-org/tls/client.crt
      - ORDERER_TLS_CLIENTKEY_FILE=/etc/hyperledger/msp/users/Admin@audit-org/tls/client.key
    volumes:
      - ./artifacts/crypto-config/peerOrganizations/audit-org:/etc/hyperledger/msp
    depends_on:
      - orderer0
      - audit-peer
    networks:
      - landrecord

  fico-cli:
    extends:
      file: ./base/cli-base.yaml
      service: cli
    container_name: fico-cli
    environment:
      - CORE_PEER_ID=fico-cli
      - CORE_PEER_ADDRESS=fico-peer:10051
      - CORE_PEER_LOCALMSPID=FicoMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@fico-org/msp
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/users/Admin@fico-org/tls/ca.crt
      - ORDERER_TLS_CLIENTCERT_FILE=/etc/hyperledger/msp/users/Admin@fico-org/tls/client.crt
      - ORDERER_TLS_CLIENTKEY_FILE=/etc/hyperledger/msp/users/Admin@fico-org/tls/client.key
    volumes:
      - ./artifacts/crypto-config/peerOrganizations/fico-org:/etc/hyperledger/msp
    depends_on:
      - orderer0
      - fico-peer
    networks:
      - landrecord


  # web:
  #   container_name: web
  #   image: web
  #   # TODO
  #   depends_on:
  #     - orderer0
  #     - appraiser-peer
  #     - audit-peer
  #     - bank-peer
  #     - fico-peer
  #     - insurance-peer
  #     - registry-peer
  #     - title-peer
  #   networks:
  #     - landrecord
