global:
  scrape_interval: 1s
  external_labels:
    monitor: 'devopsage-monitor'

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "orderer"
    static_configs:
      - targets: ["orderer0:7049"]
  - job_name: "appraiser-peer"
    static_configs:
      - targets: ["appraiser-peer:7053"]
  - job_name: "audit-peer"
    static_configs:
      - targets: ["audit-peer:8053"]
  - job_name: "bank-peer"
    static_configs:
      - targets: ["bank-peer:9053"]
  - job_name: "fico-peer"
    static_configs:
      - targets: ["fico-peer:10053"]
  - job_name: "insurance-peer"
    static_configs:
      - targets: ["insurance-peer:11053"]
  - job_name: "municipal-peer"
    static_configs:
      - targets: ["municipal-peer:12053"]
  - job_name: "registry-peer"
    static_configs:
      - targets: ["registry-peer:13053"]
  - job_name: "revenue-peer"
    static_configs:
      - targets: ["revenue-peer:14053"]
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: node
    static_configs:
      - targets: ['node-exporter:9100']
