module.exports.LendingChaincode = 'lendingchaincode'
module.exports.RecordsChaincode = 'recordschaincode'
module.exports.LendingChannel = 'lending'
module.exports.RecordsChannel = 'records'
module.exports.QueryLendingString = 'getMortgageStatus'
module.exports.QueryStartMortgage = 'startMortgage'
module.exports.QueryRealEstateString = 'queryOwner'
module.exports.QueryRecordPurchase = 'recordPurchase'
