
# SPDX-License-Identifier: Apache-2.0
version: '2.1'

volumes:
  pgdata:
  walletstore:

networks:
  landrecord:
    external:
      name: fabric_landrecord

services:

  explorerdb.landrecord:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.landrecord
    hostname: explorerdb.landrecord
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - landrecord

  explorer.landrecord:
    image: hyperledger/explorer:latest
    container_name: explorer.landrecord
    hostname: explorer.landrecord
    environment:
      - DATABASE_HOST=explorerdb.landrecord
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=info
      - LOG_LEVEL_CONSOLE=debug
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ./config.json:/opt/explorer/app/platform/fabric/config.json
      - ./connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ../artifacts/crypto-config:/tmp/crypto
      - ./walletstore:/opt/explorer/wallet
    ports:
      - 8080:8080
    depends_on:
      explorerdb.landrecord:
        condition: service_healthy
    networks:
      - landrecord
