version: '2'

services:
  cli:
    image: hyperledger/fabric-tools:2.2.5
    tty: true
    stdin_open: true
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
    working_dir: /peer
    # command: /bin/bash
    volumes:
      - ../artifacts/orderer/:/peer/orderer
      - ../chaincode:/chaincode
      - ../artifacts/channels/:/peer/channels
