version: '2'

services:
  cli:
    image: hyperledger/fabric-tools:2.2.5
    tty: true
    stdin_open: true
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_TLS_ENABLED=true
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_TLS_ROOTCERT_FILE=/peer/crypto-config/ordererOrganizations/orderer-org/msp/tlscacerts/tlsca.orderer-org-cert.pem
      #- FABRIC_LOGGING_SPEC=DEBUG
    working_dir: /peer
    # command: /bin/bash
    volumes:
      - ../artifacts/orderer/:/peer/orderer
      - ../chaincode:/chaincode
      - ../artifacts/channels/:/peer/channels
      - ../artifacts/crypto-config:/peer/crypto-config
